package app.reyna.attribution

import java.io.BufferedReader
import java.io.Reader
import java.util.Calendar
import java.util.GregorianCalendar
import java.util.TimeZone

/**
 * Parses WhatsApp "Export chat" text.
 *
 * This is Reyna's most reliable source of attribution. A file sitting in
 * WhatsApp's media folder carries no record of who sent it or when it was
 * posted; the export does, exactly, going back years. Notification history
 * cannot be backfilled, so without this every file that predates installation
 * stays anonymous forever.
 *
 * It runs **on the device, never on a server**. The export contains every
 * message the group ever sent and Reyna needs about two percent of it. Parsing
 * locally and persisting only the attachment rows is what makes the promise
 * checkable: with the phone in airplane mode, an import still works.
 *
 * Port of the Go implementation in `internal/whatsapp/export`. The two are kept
 * behaviourally identical and share test fixtures; if you change one, change
 * both.
 *
 * Parsing is deliberately forgiving. Exports differ by platform, WhatsApp
 * version, locale and phone, and an unrecognised line should cost one message
 * rather than the whole file.
 */
object ExportParser {

    /** One parsed line of an export. */
    data class Message(
        /**
         * Message time as written in the export, interpreted in the supplied
         * zone. Exports carry no timezone, so this is wall-clock time in
         * whatever zone the exporting phone was set to.
         */
        val postedAtMillis: Long,
        /** Display name as WhatsApp rendered it. Empty for system messages. */
        val sender: String,
        /** Body, with continuation lines joined by newlines. */
        val text: String,
        /** Filename when this message carried a file. Empty otherwise. */
        val attachmentName: String = "",
        /**
         * An attachment the export did not include (an export taken "without
         * media"). The name is unknown but the sender and time are not, which
         * is enough to attribute a file that landed in the same chat at the
         * same moment.
         */
        val mediaOmitted: Boolean = false,
        /** Generated by WhatsApp rather than a person. */
        val system: Boolean = false,
        val line: Int = 0,
    ) {
        val hasAttachment: Boolean get() = attachmentName.isNotEmpty() || mediaOmitted
    }

    /**
     * How the day and month fields were read.
     *
     * [proven] is true when the file itself settled it: some date had a first
     * field above 12, which only day-first explains. When false the order came
     * from the caller's default and every date in the file may be wrong by up
     * to eleven months, so the UI must be able to say which reading it used.
     */
    data class DateOrder(val dayFirst: Boolean, val proven: Boolean) {
        override fun toString(): String {
            val order = if (dayFirst) "DD/MM" else "MM/DD"
            return if (proven) "$order (proven by the file)" else "$order (assumed)"
        }
    }

    data class Result(
        val messages: List<Message>,
        val dateOrder: DateOrder,
        /** Lines that began no message and continued none. */
        val unparsedLines: Int,
    ) {
        /** Only the messages that carried a file, named or not. */
        fun attachments(): List<Message> = messages.filter { it.hasAttachment }
    }

    /**
     * Day-first is the right default for the countries WhatsApp is largest in,
     * India included. Only consulted when nothing in the file settles it.
     */
    data class Options(
        val defaultDayFirst: Boolean = true,
        val timeZone: TimeZone = TimeZone.getDefault(),
    )

    /**
     * Matches the timestamp-and-sender prefix that begins every message.
     *
     *     [12/08/2026, 21:14:03] Rahul Verma: text     iOS, bracketed, seconds
     *     12/08/2026, 21:14 - Rahul Verma: text        Android, dash separator
     *     [8/12/26, 9:14:03 PM] Rahul: text            12-hour, two-digit year
     *     12.08.2026, 21:14 - Rahul: text              dot separators
     *
     * The AM/PM group allows any non-alphanumeric run before the marker rather
     * than a literal space, because iOS 17 and later emit U+202F there. A
     * pattern written with \s silently fails on every message from a recent
     * iPhone.
     */
    private val HEADER = Regex(
        """^\[?\s*(\d{1,4})[/.\-](\d{1,2})[/.\-](\d{2,4}),?\s+(\d{1,2}):(\d{2})(?::(\d{2}))?\s*(?:[^\d\w]?\s*([APap][._]?[Mm][._]?))?\s*]?\s*(?:-\s*)?(.*)$"""
    )

    /** iOS: `<attached: NAME>`. Some builds use non-ASCII angle quotes. */
    private val ATTACHED = Regex("""[<‹]attached:\s*(.+?)\s*[>›]""")

    /**
     * Android: `NAME (file attached)`.
     *
     * The parenthetical is localised, so the filename shape carries the match
     * and the bracketed text only has to exist. Matching the English wording
     * alone would drop every attachment from a non-English export.
     */
    private val FILE_ATTACHED = Regex("""^(\S.*?\.[A-Za-z0-9]{1,8})\s*[(（]([^)）]{2,40})[)）]\s*$""")

    /**
     * The placeholder left when an export excludes media: `<Media omitted>`,
     * `<Multimedia omitido>`, `<Medien ausgelassen>` and so on.
     *
     * Matched by shape rather than wording, for the same reason as above. What
     * does not vary: one short bracketed phrase carrying no filename.
     */
    private val MEDIA_OMITTED = Regex("""^[<‹][^<>‹›]{1,60}[>›]$""")

    /**
     * Direction and byte-order marks WhatsApp sprinkles through iOS exports.
     * They sit at the start of lines and around timestamps, and any anchored
     * pattern fails on them. Stripped before anything else runs.
     */
    private val INVISIBLE = mapOf(
        '‎' to "", // LEFT-TO-RIGHT MARK
        '‏' to "", // RIGHT-TO-LEFT MARK
        '﻿' to "", // ZERO WIDTH NO-BREAK SPACE
        '​' to "", // ZERO WIDTH SPACE
        ' ' to " ", // NO-BREAK SPACE
        ' ' to " ", // NARROW NO-BREAK SPACE (iOS 17+, before AM/PM)
    )

    /**
     * WhatsApp's own messages, which have no sender. Only consulted for lines
     * with no "Name: " prefix, so a person writing "you deleted this message"
     * is not misread as a notice.
     */
    private val SYSTEM_PREFIXES = listOf(
        "messages and calls are end-to-end encrypted",
        "messages to this chat and calls are now secured",
        "you created group",
        "you were added",
        "this message was deleted",
        "you deleted this message",
        "missed voice call",
        "missed video call",
        "changed the subject",
        "changed this group's icon",
        "added you",
        "security code changed",
        "disappearing messages",
        "joined using this group's invite link",
    )

    private data class Raw(
        val first: Int, val second: Int, val year: Int,
        val hour: Int, val minute: Int, val sec: Int,
        val ampm: String, var rest: String, val lineNo: Int,
    )

    fun parse(reader: Reader, opts: Options = Options()): Result {
        val raws = ArrayList<Raw>()
        var unparsed = 0
        var lineNo = 0
        var maxFirst = 0
        var maxSecond = 0

        BufferedReader(reader).forEachLine { rawLine ->
            lineNo++
            val line = stripInvisible(rawLine)
            if (line.isBlank()) return@forEachLine

            val m = HEADER.find(line)
            if (m == null) {
                // A continuation: multi-line messages carry no timestamp after
                // the first line.
                if (raws.isNotEmpty()) raws.last().rest += "\n" + line else unparsed++
                return@forEachLine
            }

            val g = m.groupValues
            var first = g[1].toIntOrNull() ?: 0
            var second = g[2].toIntOrNull() ?: 0
            var year = g[3].toIntOrNull() ?: 0

            // A four-digit leading field means year-first (2026-08-12), which
            // is unambiguous.
            if (first > 31 && g[1].length == 4) {
                val y = first; first = second; second = year; year = y
            }

            if (first > maxFirst) maxFirst = first
            if (second > maxSecond) maxSecond = second

            raws.add(
                Raw(
                    first = first, second = second, year = year,
                    hour = g[4].toIntOrNull() ?: 0,
                    minute = g[5].toIntOrNull() ?: 0,
                    sec = g[6].toIntOrNull() ?: 0,
                    ampm = g[7].replace(".", "").replace("_", "").uppercase(),
                    rest = g[8], lineNo = lineNo,
                )
            )
        }

        val order = resolveDateOrder(maxFirst, maxSecond, opts.defaultDayFirst)
        val messages = ArrayList<Message>(raws.size)
        for (r in raws) {
            val msg = build(r, order, opts.timeZone)
            if (msg == null) unparsed++ else messages.add(msg)
        }
        return Result(messages, order, unparsed)
    }

    fun parse(text: String, opts: Options = Options()): Result = parse(text.reader(), opts)

    private fun stripInvisible(s: String): String {
        if (s.none { INVISIBLE.containsKey(it) }) return s
        val sb = StringBuilder(s.length)
        for (c in s) sb.append(INVISIBLE[c] ?: c.toString())
        return sb.toString()
    }

    /**
     * Decides day-first vs month-first.
     *
     * A single line can never settle this: 08/12 is the 8th of December or the
     * 12th of August depending on the phone. Across a whole export, any value
     * above 12 in one position rules that position out as a month. When neither
     * position ever exceeds 12 the file is genuinely ambiguous and the caller's
     * default applies, recorded as unproven so the reading can be surfaced.
     */
    internal fun resolveDateOrder(maxFirst: Int, maxSecond: Int, defaultDayFirst: Boolean): DateOrder = when {
        maxFirst > 12 && maxSecond <= 12 -> DateOrder(dayFirst = true, proven = true)
        maxSecond > 12 && maxFirst <= 12 -> DateOrder(dayFirst = false, proven = true)
        else -> DateOrder(dayFirst = defaultDayFirst, proven = false)
    }

    private fun build(r: Raw, order: DateOrder, tz: TimeZone): Message? {
        var day = r.first
        var month = r.second
        if (!order.dayFirst) { day = r.second; month = r.first }

        var year = r.year
        when {
            // WhatsApp did not exist before 2009, so a two-digit year is always
            // this century.
            year < 100 -> year += 2000
            year < 1000 -> return null
        }

        var hour = r.hour
        when (r.ampm) {
            "PM" -> if (hour < 12) hour += 12
            "AM" -> if (hour == 12) hour = 0
        }

        if (month !in 1..12 || day !in 1..31 || hour > 23 || r.minute > 59 || r.sec > 59) return null

        val cal = GregorianCalendar(tz).apply {
            isLenient = false
            clear()
            set(year, month - 1, day, hour, r.minute, r.sec)
        }
        // Non-lenient rejects impossible dates (31 April) rather than rolling
        // them into the next month.
        val millis = try {
            cal.timeInMillis
        } catch (_: IllegalArgumentException) {
            return null
        }
        if (cal.get(Calendar.DAY_OF_MONTH) != day || cal.get(Calendar.MONTH) != month - 1) return null

        val (sender, body) = splitSender(r.rest)
        val attachment = findAttachment(body)
        return Message(
            postedAtMillis = millis,
            sender = sender,
            text = body,
            attachmentName = attachment ?: "",
            mediaOmitted = attachment == null && isMediaOmitted(body),
            system = sender.isEmpty() && looksLikeSystemMessage(body),
            line = r.lineNo,
        )
    }

    /**
     * Separates "Name: body" from a system line that has no sender.
     *
     * Splitting on the **first** ": " is deliberate. Display names can contain
     * a colon and message bodies contain them constantly ("link: https://..."),
     * so splitting on the last or on any colon misattributes messages. The
     * first separator is the only one WhatsApp itself guarantees.
     */
    internal fun splitSender(rest: String): Pair<String, String> {
        val idx = rest.indexOf(": ")
        if (idx < 0) {
            // A sender with an empty message still ends in a colon.
            val t = rest.trimEnd(' ')
            if (t.endsWith(":")) {
                val cand = t.dropLast(1).trim()
                if (plausibleSenderName(cand)) return cand to ""
            }
            return "" to rest
        }
        val cand = rest.substring(0, idx).trim()
        if (!plausibleSenderName(cand)) return "" to rest
        return cand to rest.substring(idx + 2)
    }

    /**
     * Rejects candidates that are really the start of a system message.
     * Display names are short and are not sentences; WhatsApp's notices are
     * longer and read as prose. Without this, "You created group: Sem 5 CS"
     * invents a contact called "You created group".
     */
    private fun plausibleSenderName(s: String): Boolean {
        if (s.isEmpty() || s.length > 80) return false
        if (s.any { it == '\n' || it == '\t' }) return false
        val lower = s.lowercase()
        if (SYSTEM_PREFIXES.any { lower.startsWith(it) || lower.contains(it) }) return false
        // Contact names are rarely more than a few words; anything longer is prose.
        return s.trim().split(Regex("\\s+")).size <= 6
    }

    private fun looksLikeSystemMessage(body: String): Boolean {
        val lower = body.trim().lowercase()
        return SYSTEM_PREFIXES.any { lower.contains(it) }
    }

    /** Extracts the filename from either platform's notation, or null. */
    internal fun findAttachment(body: String): String? {
        val t = body.trim()
        ATTACHED.find(t)?.groupValues?.get(1)?.trim()?.let { if (it.isNotEmpty()) return it }
        FILE_ATTACHED.find(t)?.groupValues?.get(1)?.trim()?.let {
            if (looksLikeFilename(it)) return it
        }
        return null
    }

    /**
     * Keeps "IMG-20260818-WA0001.jpg (file attached)" while rejecting
     * "see you at 8 (bring notes.pdf)".
     */
    private fun looksLikeFilename(s: String): Boolean {
        if (s.isEmpty() || s.length > 260) return false
        val dot = s.lastIndexOf('.')
        if (dot <= 0 || dot == s.length - 1) return false
        if (!s.substring(dot + 1).all { it.isLetterOrDigit() && it.code < 128 }) return false
        return s.trim().split(Regex("\\s+")).size <= 8
    }

    /**
     * Whether the body is a placeholder for an attachment the export left out.
     * Callers must test the named forms first; by the time this runs, a
     * bracketed phrase with no filename can only be a placeholder.
     */
    internal fun isMediaOmitted(body: String): Boolean {
        val t = body.trim()
        if (!MEDIA_OMITTED.matches(t)) return false
        // A bracketed phrase naming a file is an attachment we failed to parse,
        // not an omission. Report nothing rather than the wrong thing.
        return !looksLikeFilename(t.substring(1, t.length - 1).trim())
    }
}
